version: "3"
services:
  web:
    build:
      context: . #where is the files to be pulled
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #do not map the node_modules into the container
      - .:/app #the current folder of local to the app folder inside the container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
